name: task_manager_app
description: "A new Flutter project."

publish_to: 'none' # Keeps the project private

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pin_code_fields: ^8.0.1
  http: ^1.2.2
  shared_preferences: ^2.3.2
  flutter_svg: ^2.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

# Add custom fonts here if needed, following the structure:
# fonts:
#   - family: CustomFont
#     fonts:
#       - asset: fonts/CustomFont-Regular.ttf
